### ISSUE TITLE
Congrat sounds not playing

### ISSUE THREAD

**Issue by alealclag** [AnKing-VIP/anki-audiovisual-feedback#14]
One day, congrat sounds stopped to work. Start sounds work fine, but I cannot make the congrat sounds work eversince (it used to work before).

Settings seem to be alright, and I've also tried using ther audio files, but nothing
![image](https://github.com/user-attachments/assets/fab8e275-8bd9-4ccb-a636-e78daf8e2c77)

**Comment by Omnia-iungitur** [comment]
Same problem
