### ISSUE TITLE
GitHub wiki for uploading theme

### ISSUE THREAD

**Issue by Foxy-null** [AnKing-VIP/anki-audiovisual-feedback#8]
I want something like [Recolor addon wiki](https://github.com/AnKing-VIP/AnkiRecolor/wiki) for this addon

**Comment by abdnh** [comment]
I added a basic wiki page, mostly rephrasing and expanding on the description in the readme: https://github.com/AnKing-VIP/anki-audiovisual-feedback/wiki

@Foxy-null let us know if you feel something is still unclear!

**Comment by Foxy-null** [comment]
Thank you so much!!!
BTW, Is there any way to upload my theme on wiki page?

It would be very useful to have [instructions for uploading themes](https://github.com/AnKing-VIP/AnkiRecolor/wiki/How-to-upload-your-theme-to-the-wiki) and a [list](https://github.com/AnKing-VIP/AnkiRecolor/wiki/Themes) of uploaded themes.

Thank you.

**Comment by abdnh** [comment]
That'd be great. I'll update the page tomorrow, then you can add your theme there!

**Comment by abdnh** [comment]
OK, feel free to add your theme now. The instructions are basically the same as in Recolor.

**Comment by Foxy-null** [comment]
tysm!!!!

**Comment by Foxy-null** [comment]
Hi @abdnh , sorry to have bothered you so many times. I'm ready to upload my theme, but I don't have permissions to create new pages on the GitHub Wiki. Could you please check your publishing permissions again?

**Comment by Foxy-null** [comment]
What I see:
![image](https://github.com/AnKing-VIP/anki-audiovisual-feedback/assets/72304646/bd84ae7f-7297-4b6c-8dd3-d355732ea8d6)

What I expected:
![image](https://github.com/AnKing-VIP/anki-audiovisual-feedback/assets/72304646/0e9adbc7-74bd-485a-981b-ee68b25fe311)

**Comment by Foxy-null** [comment]
Thank you again!
